#    ________ ________
#   |\  _____\\  _____\
#   \ \  \__/\ \  \__/
#    \ \   __\\ \   __\
#     \ \  \_| \ \  \_|
#      \ \__\   \ \__\
#       \|__|    \|__|
#         FunkyFeather

  # change logs v1.3.0:
    # - added more customizations to the feather
    # - messages config now in msg.yml
    # actual placeholders: (non-compatible with PAPI)
      # %ff_name%
      # %player%

UpdateLogger: true

Vault:
  enabled: true
  give-cost: 10
  use-cost: 5

Feather:
  Material: FEATHER
  Name: "&2Funky Feather" # this is %ff_name%
  Lore:
    - "&eSpecial Item"
    - "&7Protects your inventory but"
    - "&7gets consumed on death if"
    - "&7in your inventory."
  Enchant:
    glint: true
    enchants:
      - "FIRE_ASPECT, 2"
    effects:
      mode: "IN_HAND" # IN_HAND / INVENTORY TO ACTIVATE THE EFFECTS
      effects:
      - "POISON 0 0" # 0 to infinite

Actions:
  event1:
    type: "respawn"
    enabled: true
    do:
      - "command: eco set %player% 0"
      - "msg: &cYou lost your money!"
      - "c_msg: &cyou can't get your money back"

  event2:
    type: "die"
    enabled: false
    do:
      - "command: ban %player%"

respawn-zone:
  enabled: true

  zone: