main: fun.Entt.FunkyFeather.FunkyFeather
version: 1.1.1
name: FunkyFeather
authors: [Enttbot]
description: "Keep items or exp on death if you have the Funky Feather"
api-version: "1.13"
softdepend: [Vault]

commands:
  funkyfeather:
    description: main command of ff.
    aliases:
      - ff